/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1.views;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import proyecto1.controllers.AuthController;
import proyecto1.controllers.UserController;

/**
 *
 * @author carlo
 */
public class UserDashboard extends javax.swing.JFrame {

    private String fotoPath = "";

    /**
     * Creates new form UserDashboard
     */
    public UserDashboard() {
        initComponents();
    }

    public void cargarDatos(String user) {
        String[] datosUsuario = AuthController.getUserData(user);

        jLabelUsuario.setText("Usuario: " + datosUsuario[0]);
        jLabelNombre.setText("Nombre: " + datosUsuario[2]);
        jLabelApellido.setText("Apellido: " + datosUsuario[3]);
        jLabelFecNac.setText("Fecha de Nacimiento: " + datosUsuario[4]);
        jLabelCorreo.setText("Correo: " + datosUsuario[5]);
        jLabelTel.setText("Telefono: " + datosUsuario[6]);
        Icon userImage = new ImageIcon(new ImageIcon(datosUsuario[7]).getImage()
                .getScaledInstance(lblImg.getWidth(), lblImg.getHeight(), 0));
        lblImg.setIcon(userImage);
        if (AuthController.checkUserPrivileges(datosUsuario[0])) {
            jLblTipoUsuario.setText("Tipo de Usuario: Administrador");
        } else {
            jLblTipoUsuario.setText("Tipo de Usuario: Usuario Normal");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelUsuario = new javax.swing.JTabbedPane();
        jPanelGeneral = new javax.swing.JPanel();
        lblImg = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelApellido = new javax.swing.JLabel();
        jLabelFecNac = new javax.swing.JLabel();
        jLabelCorreo = new javax.swing.JLabel();
        jLabelTel = new javax.swing.JLabel();
        jLblTipoUsuario = new javax.swing.JLabel();
        jBtnEdit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        JPanelContactos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtContactoBusqueda = new javax.swing.JTextField();
        btnBuscarUsuario = new javax.swing.JButton();
        btnBuscarNombre = new javax.swing.JButton();
        btnBuscarApellido = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListContactosBuscados = new javax.swing.JList<>();
        btnAgregarContacto = new javax.swing.JButton();
        btnEditContactos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelUsuario.setText("Usuario:");

        jLabelNombre.setText("Nombre:");

        jLabelApellido.setText("Apellido:");

        jLabelFecNac.setText("Fecha de Nacimiento:");

        jLabelCorreo.setText("Correo:");

        jLabelTel.setText("Telefono:");

        jLblTipoUsuario.setText("Tipo Usuario: ");

        jBtnEdit.setText("Editar Usuario");
        jBtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditActionPerformed(evt);
            }
        });

        jButton1.setText("Darse de baja");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelGeneralLayout = new javax.swing.GroupLayout(jPanelGeneral);
        jPanelGeneral.setLayout(jPanelGeneralLayout);
        jPanelGeneralLayout.setHorizontalGroup(
            jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeneralLayout.createSequentialGroup()
                .addGroup(jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelGeneralLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelGeneralLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jButton1)))
                .addGap(46, 46, 46)
                .addGroup(jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelGeneralLayout.createSequentialGroup()
                        .addComponent(jLabelTel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelGeneralLayout.createSequentialGroup()
                        .addGroup(jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCorreo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelApellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelFecNac, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                            .addGroup(jPanelGeneralLayout.createSequentialGroup()
                                .addComponent(jLabelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(77, 77, 77))
                    .addGroup(jPanelGeneralLayout.createSequentialGroup()
                        .addGroup(jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblTipoUsuario))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanelGeneralLayout.setVerticalGroup(
            jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeneralLayout.createSequentialGroup()
                .addGroup(jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelGeneralLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabelUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelNombre)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelApellido)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelFecNac)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelCorreo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGeneralLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelTel)
                .addGap(18, 18, 18)
                .addComponent(jLblTipoUsuario)
                .addGap(18, 18, 18)
                .addGroup(jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnEdit)
                    .addComponent(jButton1))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jPanelUsuario.addTab("General", jPanelGeneral);

        jLabel3.setText("Buscar Contactos");

        txtContactoBusqueda.setText("jTextField1");

        btnBuscarUsuario.setText("Buscar Por Usuario");
        btnBuscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarUsuarioActionPerformed(evt);
            }
        });

        btnBuscarNombre.setText("Buscar Por Nombre");
        btnBuscarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarNombreActionPerformed(evt);
            }
        });

        btnBuscarApellido.setText("Buscar Por Apellido");
        btnBuscarApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarApellidoActionPerformed(evt);
            }
        });

        jLabel4.setText("Resultados:");

        jListContactosBuscados.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListContactosBuscados);

        btnAgregarContacto.setText("Agregar Contacto");
        btnAgregarContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarContactoActionPerformed(evt);
            }
        });

        btnEditContactos.setText("Editar Mis Contactos");
        btnEditContactos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditContactosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanelContactosLayout = new javax.swing.GroupLayout(JPanelContactos);
        JPanelContactos.setLayout(JPanelContactosLayout);
        JPanelContactosLayout.setHorizontalGroup(
            JPanelContactosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelContactosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(250, 250, 250))
            .addGroup(JPanelContactosLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(JPanelContactosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelContactosLayout.createSequentialGroup()
                        .addGroup(JPanelContactosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtContactoBusqueda)
                            .addGroup(JPanelContactosLayout.createSequentialGroup()
                                .addComponent(btnBuscarNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                                .addComponent(btnBuscarApellido)
                                .addGap(44, 44, 44)
                                .addComponent(btnBuscarUsuario)))
                        .addGap(58, 58, 58))
                    .addGroup(JPanelContactosLayout.createSequentialGroup()
                        .addGroup(JPanelContactosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditContactos, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(JPanelContactosLayout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(btnAgregarContacto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPanelContactosLayout.setVerticalGroup(
            JPanelContactosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelContactosLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtContactoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(JPanelContactosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarUsuario)
                    .addComponent(btnBuscarNombre)
                    .addComponent(btnBuscarApellido))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAgregarContacto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditContactos)
                .addGap(23, 23, 23))
        );

        jPanelUsuario.addTab("Contactos", JPanelContactos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelUsuario)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditActionPerformed

        String textoUsuario = jLabelUsuario.getText();

        // Comprueba si el texto comienza con "Usuario: "
        if (textoUsuario.startsWith("Usuario: ")) {
            // Obtiene el nombre de usuario eliminando "Usuario: "
            String nombreUsuario = textoUsuario.substring("Usuario: ".length());

            // Pasa el nombre de usuario a la ventana de edición
            EditUser edit = new EditUser();
            edit.cargarDatos(nombreUsuario);
            edit.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "El texto no tiene el formato esperado.");
        }
    }//GEN-LAST:event_jBtnEditActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarUsuarioActionPerformed
        DefaultListModel<String> modeloListaContactos = (DefaultListModel<String>) jListContactosBuscados.getModel();
        if (txtContactoBusqueda.getText() != null) {
            String Usuario = txtContactoBusqueda.getText();
            String Information = UserController.getContactoByUser(Usuario);
            if (Information.length() > 0) {
                modeloListaContactos.clear();
                modeloListaContactos.addElement(Information);
            } else {
                modeloListaContactos.clear();
                modeloListaContactos.addElement("No se encontraron datos");
            }
        }
    }//GEN-LAST:event_btnBuscarUsuarioActionPerformed

    private void btnBuscarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarNombreActionPerformed
        DefaultListModel<String> modeloListaContactos = (DefaultListModel<String>) jListContactosBuscados.getModel();
        if (txtContactoBusqueda.getText() != null) {
            String LastName = txtContactoBusqueda.getText();
            List<String[]> Information = UserController.getContactoByLastName(LastName);
            if (!Information.isEmpty()) {

                for (int i = 0; i < Information.size(); i++) {
                    String[] userData = Information.get(i);

                    String user = userData[0];
                    String name = userData[2];
                    String lastName = userData[3];
                    modeloListaContactos.addElement(user+"|"+name+"|"+lastName);
                }

            } else {
                modeloListaContactos.clear();
                modeloListaContactos.addElement("No se encontraron datos");
            }
        }
    }//GEN-LAST:event_btnBuscarNombreActionPerformed

    private void btnBuscarApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarApellidoActionPerformed
        DefaultListModel<String> modeloListaContactos = (DefaultListModel<String>) jListContactosBuscados.getModel();
        if (txtContactoBusqueda.getText() != null) {
            String nameUser = txtContactoBusqueda.getText();
            List<String[]> Information = UserController.getContactoByName(nameUser);
            if (!Information.isEmpty()) {

                for (int i = 0; i < Information.size(); i++) {
                    String[] userData = Information.get(i);

                    String user = userData[0];
                    String name = userData[2];
                    String lastName = userData[3];
                    modeloListaContactos.addElement(user+"|"+name+"|"+lastName);
                }

            } else {
                modeloListaContactos.clear();
                modeloListaContactos.addElement("No se encontraron datos");
            }
        }
    }//GEN-LAST:event_btnBuscarApellidoActionPerformed

    private void btnAgregarContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarContactoActionPerformed

        DefaultListModel<String> modeloListaContactos = (DefaultListModel<String>) jListContactosBuscados.getModel();
        String seleccionado = jListContactosBuscados.getSelectedValue();

        if (seleccionado != null) {
            // Divide la cadena en partes usando el carácter "|"
            String[] partes = seleccionado.split("\\|");

            if (partes.length > 0) {
                // Obtiene la primera parte, que debería ser el nombre de usuario
                String nombreUsuario = partes[0].trim();
                //UserController.eliminarUsuario(nombreUsuario);

            } else {
                JOptionPane.showMessageDialog(this, "No se encontró el nombre de usuario en el elemento seleccionado.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Ningún elemento seleccionado.");
        }
    }//GEN-LAST:event_btnAgregarContactoActionPerformed

    private void btnEditContactosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditContactosActionPerformed
        String textoUsuario = jLabelUsuario.getText();

        // Comprueba si el texto comienza con "Usuario: "
        if (textoUsuario.startsWith("Usuario: ")) {
            // Obtiene el nombre de usuario eliminando "Usuario: "
            String nombreUsuario = textoUsuario.substring("Usuario: ".length());

            // Pasa el nombre de usuario a la ventana de edición
            Contacts edit = new Contacts(nombreUsuario);
            edit.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "El texto no tiene el formato esperado.");
        }
    }//GEN-LAST:event_btnEditContactosActionPerformed
    private boolean isValidEmail(String email) {
        String regex = "^[A-Za-z0-9+_.-]+@(.+)$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(email);
        return matcher.matches();
    }

    private boolean isValidPhone(String phone) {
        String regex = "^\\d{8}$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(phone);
        return matcher.matches();
    }

    private boolean isValidDate(String date) {
        String regex = "^\\d{4}-\\d{2}-\\d{2}$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(date);
        return matcher.matches();
    }

    private String getFileExtension(File file) {
        String extension = "";
        String fileName = file.getName();
        int lastIndex = fileName.lastIndexOf(".");
        if (lastIndex > 0) {
            extension = fileName.substring(lastIndex + 1).toLowerCase();
        }
        return extension;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelContactos;
    private javax.swing.JButton btnAgregarContacto;
    private javax.swing.JButton btnBuscarApellido;
    private javax.swing.JButton btnBuscarNombre;
    private javax.swing.JButton btnBuscarUsuario;
    private javax.swing.JButton btnEditContactos;
    private javax.swing.JButton jBtnEdit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelCorreo;
    private javax.swing.JLabel jLabelFecNac;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTel;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JLabel jLblTipoUsuario;
    private javax.swing.JList<String> jListContactosBuscados;
    private javax.swing.JPanel jPanelGeneral;
    private javax.swing.JTabbedPane jPanelUsuario;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblImg;
    private javax.swing.JTextField txtContactoBusqueda;
    // End of variables declaration//GEN-END:variables
}
